.info = "Permanent hourly archive with guarded retention pruning. Calls maintain_iotawatt_retention() daily at 03:40 America/Denver, retains 14 days of raw data and 30 days of minute data, and alerts if archive or enabled prune success is older than 36 hours." |
(.nodes[] | select(.id=="iotawatt_archive_daily") | .name) = "Daily archive + prune 03:40" |
(.nodes[] | select(.id=="iotawatt_archive_manual") | .name) = "Manual archive + prune" |
(.nodes[] | select(.id=="iotawatt_watchdog_hourly") | .name) = "Retention watchdog hourly" |
(.nodes[] | select(.id=="iotawatt_archive_call_tpl") | .name) = "CALL archive + guarded prune" |
(.nodes[] | select(.id=="iotawatt_archive_call_tpl") | .template) = "CALL maintain_iotawatt_retention();" |
(.nodes[] | select(.id=="iotawatt_archive_mysql") | .name) = "Archive + prune retention" |
(.nodes[] | select(.id=="iotawatt_archive_success") | .name) = "Retention succeeded" |
(.nodes[] | select(.id=="iotawatt_archive_success") | .func) = "msg.payload = { status: 'success', job: 'maintain_iotawatt_retention', completed_at: new Date().toISOString() };\nnode.status({fill:'green',shape:'dot',text:'archive + prune succeeded'});\nreturn msg;" |
(.nodes[] | select(.id=="iotawatt_watchdog_query_tpl") | .name) = "Check archive + prune success" |
(.nodes[] | select(.id=="iotawatt_watchdog_query_tpl") | .template) = "SELECT\n    LastArchiveSuccessUTC,\n    TIMESTAMPDIFF(HOUR, LastArchiveSuccessUTC, UTC_TIMESTAMP()) AS ArchiveAgeHours,\n    LastPruneSuccessUTC,\n    TIMESTAMPDIFF(HOUR, LastPruneSuccessUTC, UTC_TIMESTAMP()) AS PruneAgeHours,\n    PruningEnabled,\n    ReadyToPrune\nFROM v_iotawatt_pruning_readiness\nWHERE Id=1;" |
(.nodes[] | select(.id=="iotawatt_watchdog_mysql") | .name) = "Read retention health" |
(.nodes[] | select(.id=="iotawatt_watchdog_check") | .name) = "Alert if older than 36h" |
(.nodes[] | select(.id=="iotawatt_watchdog_check") | .func) = "const rows = Array.isArray(msg.payload) ? msg.payload : [];\nconst row = rows[0] || {};\nconst archiveAge = Number(row.ArchiveAgeHours);\nconst pruneAge = Number(row.PruneAgeHours);\nconst pruningEnabled = Number(row.PruningEnabled) === 1 || row.PruningEnabled === true;\nconst archiveStale = !row.LastArchiveSuccessUTC || !Number.isFinite(archiveAge) || archiveAge > 36;\nconst pruneStale = pruningEnabled && (!row.LastPruneSuccessUTC || !Number.isFinite(pruneAge) || pruneAge > 36);\nconst stale = archiveStale || pruneStale;\n\nif (!stale) {\n    const pruneText = pruningEnabled ? `${pruneAge}h` : 'disabled';\n    node.status({fill:'green',shape:'dot',text:`archive ${archiveAge}h, prune ${pruneText}`});\n    msg.payload = {\n        status: 'healthy',\n        archive_age_hours: archiveAge,\n        prune_age_hours: pruningEnabled ? pruneAge : null,\n        pruning_enabled: pruningEnabled,\n        last_archive_utc: row.LastArchiveSuccessUTC,\n        last_prune_utc: row.LastPruneSuccessUTC\n    };\n    return [null, msg];\n}\n\nnode.status({fill:'red',shape:'ring',text:'retention stale'});\nconst now = Date.now();\nconst lastAlert = flow.get('iotawattRetentionLastStaleAlert') || 0;\nif (now - lastAlert < 12 * 60 * 60 * 1000) return [null, null];\nflow.set('iotawattRetentionLastStaleAlert', now);\nmsg.title = 'IotaWatt retention is stale';\nmsg.payload = `IotaWatt retention health failed. Archive last success UTC: ${row.LastArchiveSuccessUTC || 'never'} (age ${Number.isFinite(archiveAge) ? archiveAge : 'unknown'}h). Prune enabled: ${pruningEnabled}. Prune last success UTC: ${row.LastPruneSuccessUTC || 'never'} (age ${Number.isFinite(pruneAge) ? pruneAge : 'unknown'}h).`;\nmsg.device = global.get('BradPhoneNM') || 'pixel8';\nreturn [msg, null];" |
(.nodes[] | select(.id=="iotawatt_retention_catch") | .name) = "Catch retention DB errors" |
(.nodes[] | select(.id=="iotawatt_retention_error") | .name) = "Build retention failure alert" |
(.nodes[] | select(.id=="iotawatt_retention_error") | .func) = "const detail = (msg.error && msg.error.message) ? msg.error.message : String(msg.payload || 'unknown database error');\nconst now = Date.now();\nconst lastAlert = flow.get('iotawattRetentionLastErrorAlert') || 0;\nif (now - lastAlert < 30 * 60 * 1000) return null;\nflow.set('iotawattRetentionLastErrorAlert', now);\nmsg.title = 'IotaWatt retention failure';\nmsg.payload = `IotaWatt archive/prune/watchdog database error: ${detail}. Guarded pruning stops on validation failure.`;\nmsg.device = global.get('BradPhoneNM') || 'pixel8';\nreturn msg;" |
(.nodes[] | select(.id=="iotawatt_retention_pushover") | .title) = "IotaWatt retention alert" |
(.nodes[] | select(.id=="iotawatt_retention_pushover") | .name) = "IotaWatt retention alert" |
(.nodes[] | select(.id=="iotawatt_retention_debug") | .name) = "Retention health/status" |
(.nodes[] | select(.id=="iotawatt_retention_comment") | .name) = "Permanent hourly archive + guarded 14d raw / 30d minute pruning" |
(.nodes[] | select(.id=="iotawatt_retention_comment") | .info) = "Daily maintenance archives complete hours first, validates exact archive coverage, then prunes source rows in bounded timestamp-key batches. Pruning requires GrafanaMigrated=1, ConsumersMigrated=1, and PruningEnabled=1; any validation mismatch aborts deletion and is logged."
