{
 "title": "IotaWatt Energy",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Total Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(TotalWattHours) over (order by DateDTS ))\nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Tesla",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(EVHours) over (order by DateDTS ))\nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "AC",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(ACHours) over (order by DateDTS ))\nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Heat Pump",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(TotalHeatPumpHours) over (order by DateDTS ))\nFROM IotaWattHoursSolarbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Furnace",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(FurnaceHours) over (order by DateDTS ))\nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Dryer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(DryerHours) over (order by DateDTS ))\nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "All Other ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(AllOtherHours) over (order by DateDTS ))\nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  Total,\n  WaterHeater,\n  Furnace,\n  Fridge,\n  Kitchen,\n  ACTotal as \"AC\",\n  DryerTotal as \"Dryer\",\n  EVTotal as \"Tesla\",\n  RangeTotal as \"Oven\",\n  AllOther as \"All Other\"\nFROM IotaWatt\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  TotalSolar as \"Solar\",\n  TotalHeatPump as \"HeatPump\"\nFROM IotaWattSolar\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
    }
   ]
  },
  {
   "title": "Usage by Hour",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(DateDTS,1h) \n\n  ,sum(ACHours) as \"AC\"\n  ,sum(DryerHours) as \"Dryer\"\n  ,sum(RangeHours) as \"Oven\"\n  ,sum(WaterHeaterHours) as \"Water Heater\"\n  ,sum(EVHours) as \"Tesla\"\n  ,sum(FurnaceHours) as \"Furnace\"\n  ,sum(FridgeHours) as \"Fridge\"\n  ,sum(KitchenHours) as \"Kitchen\"\n  ,sum(UpstairsBedsHours) \"Upstairs Beds\"\n  ,sum(OfficeHours) as \"Office\"\n  ,sum(UtilityClosetHours) as \"Utility Closet\"\n  ,sum(AllOtherHours) as \"All Other\"\n   \nFROM IotaWattHoursbyMinute\nWHERE\n  $__timeFilter(DateDTS)\nGroup by   1\nORDER BY unix_timestamp(DateDTS)"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroupAlias(DateDTS,1h) \r\n\r\n  ,sum(TotalHeatPumpHours) as \"HeatPump\"\r\n\r\n   \r\nFROM IotaWattHoursSolarbyMinute\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\nGroup by   1\r\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(Time) AS \"time\",\n  Total\nFROM IotaWatt\nWHERE\n  $__timeFilter(Time)\nORDER BY Time"
    }
   ]
  }
 ]
}