{
 "title": "IotaWatt Live",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Current Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\navg(TotalGrid) as \"Total\"\nFROM v_iotawatt_solar_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\navg(Voltage) as \"Total\"\nFROM v_iotawatt_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\navg(Frequency) as \"Total\"\nFROM v_iotawatt_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n unix_timestamp(time) AS \"time\",\r\n  avg(WaterHeater) as \"WaterHeater\",\r\n  avg(Furnace) as \"Furnace\",\r\n  avg(Fridge) as \"Fridge\",\r\n  avg(Kitchen) as \"Kitchen\",\r\n  avg(ACTotal) as \"AC\",\r\n  avg(DryerTotal) as \"Dryer\",\r\n  avg(EVTotal) as \"Tesla\",\r\n  avg(RangeTotal) as \"Oven\",\r\n  avg(AllOther) as \"All Other\"\r\nFROM v_iotawatt_power_all\r\nWHERE\r\n  $__timeFilter(Time)\r\nGROUP BY 1\r\nORDER BY Time\r\n"
    },
    {
     "rawSql": "SELECT\r\n unix_timestamp(time) AS \"time\",\r\n  avg(TotalHeatPump) as \"HeatPump\",\r\n  avg(TotalGrid) as \"Total\"\r\n  \r\nFROM v_iotawatt_solar_power_all\r\nWHERE\r\n  $__timeFilter(Time)\r\nGROUP BY 1\r\nORDER BY Time\r\n"
    }
   ]
  },
  {
   "title": "Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(time) AS \"time\",\n  avg(WaterHeater) as \"WaterHeater\",\n  avg(Furnace) as \"Furnace\",\n  avg(Fridge) as \"Fridge\",\n  avg(Kitchen) as \"Dishwasher\",\n  avg(ACTotal) as \"AC\",\n  avg(DryerTotal) as \"Dryer\",\n  avg(EVTotal) as \"Tesla\",\n  avg(RangeTotal) as \"Oven\",\n  -- New fields added below\n  avg(UpstairsBeds) as \"Upstairs Beds\",\n  avg(Office) as \"Office\",\n  avg(UtilityCloset) as \"Utility Closet\",\n  -- All Other is now last\n  avg(AllOther) as \"All Other\"\nFROM v_iotawatt_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY Time"
    },
    {
     "rawSql": "SELECT\r\n unix_timestamp(time) AS \"time\",\r\n  avg(TotalHeatPump) as \"HeatPump\",\r\n  avg(TotalGrid) as \"Total\"\r\n\r\nFROM v_iotawatt_solar_power_all\r\nWHERE\r\n  $__timeFilter(Time)\r\nGROUP BY 1\r\nORDER BY Time\r\n"
    }
   ]
  },
  {
   "title": "Amps",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\r\n  avg(TotalHeatPump/240) as \"HeatPump\"\r\n\r\nFROM v_iotawatt_solar_power_all\r\nWHERE\r\n  $__timeFilter(Time)\r\nGROUP BY 1\r\nORDER BY Time\r\n"
    },
    {
     "rawSql": "SELECT\n unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\n  avg(WaterHeater)/120 as \"WaterHeater\",\n  avg(Furnace)/120 as \"Furnace\",\n  avg(Fridge)/120 as \"Fridge\",\n  avg(Kitchen)/120 as \"Kitchen\",\n  avg(ACTotal)/240 as \"AC\",\n  avg(DryerTotal)/240 as \"Dryer\",\n  avg(EVTotal)/240 as \"Tesla\",\n  avg(RangeTotal)/240 as \"Oven\",\n  avg(AllOther)/120 as \"All Other\"\nFROM v_iotawatt_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY Time\n"
    }
   ]
  },
  {
   "title": "Watts, Volts, and Frequency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(Total) as \"Total\"\n  ,avg(Voltage) as \"Voltage\"\n  ,avg(Frequency) as \"Frequency\"\n\nFROM v_iotawatt_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Volts and Solar",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(Total) as \"Total\"\n  ,avg(Voltage) as \"Voltage\"\nFROM v_iotawatt_power_all\nWHERE\n  $__timeFilter(Time)\nGROUP BY 1\nORDER BY 1"
    },
    {
     "rawSql": "\r\nSELECT\r\n  unix_timestamp(time)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\r\n  ,avg(TotalSolar) as \"Solar\"\r\n  FROM v_iotawatt_solar_power_all\r\nWHERE\r\n  $__timeFilter(Time)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  }
 ]
}