{
 "title": "Weather by City",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature SLC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\n  avg(value) as Temp\nFROM weatherBradley\nWHERE\n  $__timeFilter(created)\n  and\n  name =\"tempf\"\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity SLC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(value) as Humidity\nFROM weatherBradley\nWHERE\n  $__timeFilter(created)\n  and\n  name =\"humidityout\"\nGROUP BY 1\nOrder by 1"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='tempout' then vavg else null end) as 'Temperature'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('tempout')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='humidityout' then vavg else null end) as 'Humidity'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('humidityout')\nand\n$__timeFilter(created)\nGroup by  1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Rain (cumulative by event)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\"\n  ,avg(case when name='eventrain' then vavg else null end) as 'Rain'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('eventrain')\nand\n$__timeFilter(created)\nGroup by   unix_timestamp(created) \nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Combination SLC",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='tempout' then value else null end) as 'Temperature'\n  ,avg(case when name='humidityout' then value else null end) as 'Humidity'\n  ,avg(case when name='baromrel' then value else null end) as 'Pressure'\nFROM weatherBradley\nwhere\nname in ('tempout','humidityout','baromrel')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='illuminance' then vavg else null end) as 'Light'\n  ,avg(case when name='solarradiation' then vavg else null end) as 'Solar Radiation'\n\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere \nname in ('illuminance','solarradiation')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='baromrel' then vavg else null end) as 'Pressure'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('baromrel')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='windSpeed' then vavg else null end) 'Wind'\n  ,avg(case when name='windGust' then vavg else null end) 'Wind Gusts'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('windSpeed', 'WindGust')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind Speed Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,30m)\n  ,avg(case when name='windSpeed' then vavg else null end) 'Wind'\n  ,max(case when name='windGust' then vmax else null end) 'Wind Gusts'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('windSpeed', 'WindGust')\nand\n$__timeFilter(created)\nGroup by  1\nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,max(case when name='windDirection' then vmax else null end) 'Wind Direction'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere \nname in ('windDirection')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "spectraphilic-windrose-panel",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 102 },
   "targets": [
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\r\n  ,max(case when name = 'windSpeed' then vmax else null end ) as 'speed'\r\n  ,max(case when name = 'windDirection' then vmax else null end) as'direction'\r\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\r\nwhere\r\nname in ('windSpeed', 'windDirection')\r\nand\r\n$__timeFilter(created)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  }
 ]
}