{
 "title": "Thermostat",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Heater Run Time (Hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(StateStartTime)) AS \"time\"\n,(sum(case when value='heating' then runtime/3600 else 0 end)  over (order by StateStartTime)) as \"Heat Run Time\"\n\n\nFROM thermostatcalc\nWHERE\n  $__timeFilter(StateStartTime)\nORDER BY StateStartTime"
    }
   ]
  },
  {
   "title": "Gas Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(StateStartTime)) AS \"time\",\nsum(case when value='heating' then runtime/3600 else 0 end)  over (order by StateStartTime)*.45 as \"Heat Run Time\"\n\nFROM thermostatcalc\nWHERE\n  $__timeFilter(StateStartTime)\nORDER BY StateStartTime"
    }
   ]
  },
  {
   "title": "AC Run Time (Hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(StateStartTime)) AS \"time\"\n,(sum(case when value='cooling' then runtime/3600 else 0 end)  over (order by StateStartTime)) as \"AC Run Time\"\n\n\nFROM thermostatcalc\nWHERE\n  $__timeFilter(StateStartTime)\nORDER BY StateStartTime"
    }
   ]
  },
  {
   "title": "AC Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(ACHours) over (order by DateDTS ))/1000*.1\nFROM v_iotawatt_energy_all\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Blower Cost",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(DateDTS) AS \"time\",\n(sum(FurnaceHours) over (order by DateDTS ))/1000*.1\nFROM v_iotawatt_energy_all\nWHERE\n  $__timeFilter(DateDTS)\nORDER BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "HVAC Run Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(StateStartTime)) AS \"time\",\nsum(case when value='heating' then runtime/60 else null end) as \"Heat Run Time\",\nsum(case when value='cooling' then runtime/60 else null end) as \"A/C Run Time\",\nsum(case when value in ('fan only','fan') then runtime/60 else null end) as \"Fan Run Time\"\nFROM thermostatcalc\nWHERE\n  $__timeFilter(StateStartTime)\nGroup by Date(StateStartTime)\nORDER BY StateStartTime"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(date(created)) AS \"time\"\n  ,max(case when name='tempout' then vmax else null end) as 'Daily High'\n  ,min(case when name='tempout' then vmin else null end) as 'Daily Low'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE 1=1\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE 1=1\n) weather\nwhere\nname in ('tempout')\nGroup by   unix_timestamp(date(created)) \nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Gas + AC Cost",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(STR_TO_DATE(CONCAT(YEAR(StateStartTime), '-', MONTH(StateStartTime), '-01'), '%Y-%m-%d')) AS \"time\",\n  SUM(CASE WHEN value='heating' THEN runtime/3600 ELSE NULL END)*.45 AS \"Heat Run Time\"\n\nFROM thermostatcalc\nWHERE\n  $__timeFilter(StateStartTime)\nGROUP BY YEAR(StateStartTime), MONTH(StateStartTime)\nORDER BY \"time\";\n"
    },
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(STR_TO_DATE(CONCAT(YEAR(DateDTS), '-', MONTH(DateDTS), '-01'), '%Y-%m-%d')) AS \"time\",\r\n  SUM(WaterHeaterHours)/400 AS \"WaterHeaterCalculation\",\r\n    SUM(ACHours)/1000*.1 AS \"ACCost\",\r\nSUM(FurnaceHours)/1000*.1 AS \"BlowerCost\"\r\nFROM v_iotawatt_energy_all\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\nGROUP BY YEAR(DateDTS), MONTH(DateDTS)\r\nORDER BY \"time\";\r\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\nunix_timestamp(created) AS \"time\"\n,case when value='idle' then null \n      when value='heating' then 1 else null end as 'Heater'\n,case when value='idle' then null \n      when value='cooling' then 1 else null end as 'AC'\n,case when value='idle' then null\n      when value in ('fan only','fan') then 1 else null end as 'Fan'\nFROM thermostat\nWHERE\n  $__timeFilter(created)\n\nGROUP BY \nunix_timestamp(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\r\nunix_timestamp(DateDTS) AS \"time\"\r\n,ProgramNM\r\nFROM ThermostatProgram\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\n\r\n"
    }
   ]
  }
 ]
}