{
 "title": "Humidity",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n,avg(case when displayName in ('Master toilet motion') then value else null end) as 'Master Bath'\n,avg(case when displayName in ('Basement family motion') then value else null end) as 'Basement'\n,avg(case when displayName in ('Laundry motion iris on Home 3') then value else null end) as 'Laundry'\n,avg(case when displayName in ('Garage Motion on Home 3') then value else null end) as 'Garage'\n,avg(case when displayName in ('cold storage motion humidity') then value else null end) as 'Cold Storage'\n,avg(case when displayName in ('Ecowitt Remote 7') then value else null end) as 'Attic'\n,avg(case when displayName in ('Backyard Weather on Hub 2') then value else null end) as 'Outside'\n,avg(case when displayName in ('Basement Humidity') then value else null end) as 'Basement Ecowitt'\nFROM humidity\nWHERE\n  $__timeFilter(created)\nAND displayName IN (\n    'Master toilet motion',\n    'Basement family motion',\n    'Laundry motion iris on Home 3',\n    'Garage Motion on Home 3',\n    'cold storage motion humidity',\n    'Ecowitt Remote 7',\n    'Backyard Weather on Hub 2',\n    'Basement Humidity'\n)\nGROUP BY \n  1\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='humidityin' then vavg else null end) as 'Main Floor'\n\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\n$__timeFilter(created)\nAND \nname='humidityin'\nGroup by   1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity and Temp",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n,avg(case when displayName in ('Basement family motion') then value else null end) as 'Basement Humidity'\n,avg(case when displayName in ('Basement Humidity') then value else null end) as 'Basement Ecowitt Humidity'\nFROM humidity\nWHERE\n  $__timeFilter(created)\n\nGROUP BY \n1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when displayName='Basement family motion' then value else null end) as 'Basement Temperature'\n\nFROM temperatures\nwhere\n$__timeFilter(created)\nGroup by   1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\nunix_timestamp(created) AS \"time\"\n,case when value='idle' then null \n      when value='heating' then 1 else null end as 'Heater'\n,case when value='idle' then null \n      when value='cooling' then 1 else null end as 'AC'\n,case when value='idle' then null\n      when value='fan only' then 1 else null end as 'Fan'\nFROM thermostat\nWHERE\n  $__timeFilter(created)\n\nGROUP BY \nunix_timestamp(created)\nORDER BY created"
    }
   ]
  }
 ]
}