{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Upstairs ",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(created) AS \"time\"\r\n  ,avg(case when name in ('tempout','tempf') then vavg else null end) as 'Outside'\r\n  ,avg(case when name in ('tempin','tempinf') then vavg else null end) as 'Main Floor'\r\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\r\nwhere\r\nname in ('tempin','tempout','tempinf','tempf')\r\n and\r\n $__timeFilter(created)\r\nGroup by   unix_timestamp(created) \r\nORDER BY created"
    },
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\r\n,avg(case when displayName in ('Office Hue Motion Sensor') then value else null end) as 'Office'\r\n,avg(case when displayName in ('Simon motion and temp') then value else null end) as 'Boys Room'\r\n,avg(case when displayName in ('Master bed motion sensor') then value else null end) as 'Master Bed'\r\n,avg(case when displayName in ('Basement family motion') then value else null end) as 'Basement'\r\n,avg(case when displayName in ('Garage Motion on Home 3') then value else null end) as 'Garage'\r\n,avg(case when displayName in ('Cold storage water sensor') then value else null end) as 'Cold Storage'\r\n,avg(case when displayName in ('Fridge Temp') then value else null end) as 'Fridge'\r\n,avg(case when displayName in ('Freezer Temp') then value else null end) as 'Freezer'\r\n,avg(case when displayName in ('Ecowitt Remote 7') then value else null end) as 'Attic'\r\n,avg(case when displayName in ('Adrienne Office Motion ST') then value else null end) as 'Adrienne Office'\r\n\r\n\r\nFROM temperatures\r\nWHERE\r\n  $__timeFilter(created)\r\n  AND\r\n  displayName IN (\r\n    'Master bed motion sensor',\r\n    'Basement family motion',\r\n    'Garage Motion on Home 3',\r\n    'Cold storage water sensor',\r\n    'Fridge Temp',\r\n    'Ecowitt Remote 7',\r\n    'Freezer Temp',\r\n    'Simon motion and temp',\r\n    'Office Hue Motion Sensor',\r\n    'Adrienne Office Motion ST'\r\n  )\r\n  \r\nGROUP BY  1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n,avg(case when displayName in ('Master bed motion sensor') then value else null end) as Upstairs\n,avg(case when displayName in ('Basement family motion') then value else null end) as 'Basement'\n,avg(case when displayName in ('Garage Motion on Home 3') then value else null end) as 'Garage'\n,avg(case when displayName in ('Cold storage water sensor') then value else null end) as 'Cold Storage'\n,avg(case when displayName in ('Simon motion and temp') then value else null end) as 'Simon Room'\n,avg(case when displayName in ('Adrienne Office Motion ST') then value else null end) as 'Adrienne Office'\nFROM temperatures\nWHERE\n  $__timeFilter(created)\n  and\n  displayName in ('Master bed motion sensor','Basement family motion','Garage Motion on Home 3','Cold storage water sensor','Fridge Temp','Simon motion and temp','Adrienne Office Motion ST')\nGROUP BY  1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\"\n  ,avg(case when name in('tempin','tempinf') then vavg else null end) as 'Main Floor'\n  ,avg(case when name in('tempf','temp') then vavg else null end) as 'Outside'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('tempin', 'tempinf','tempf','temp')\n and\n $__timeFilter(created)\nGroup by   unix_timestamp(created) \nORDER BY created"
    }
   ]
  },
  {
   "title": "Attic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n UNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n,avg(case when displayName in ('Master bed motion sensor') then value else null end) as Upstairs\n,avg(case when displayName in ('Ecowitt Remote 7') then value else null end) as 'Attic'\nFROM temperatures\nWHERE\n  $__timeFilter(created)\n  and\n  displayName in ('Master bed motion sensor','Ecowitt Remote 7')\nGROUP BY  1\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n    UNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms AS \"time\"\n  ,avg(case when name in ('tempout','tempf') then vavg else null end) as 'Outside Temp'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('tempout','tempf')\nand\n $__timeFilter(created)\nGroup by   1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Fridge/Freezer",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n,avg(case when displayName in ('Fridge Temp') then value else null end) as 'Fridge'\n,avg(case when displayName in ('Freezer Temp') then value else null end) as 'Freezer'\nFROM temperatures\nWHERE\n  $__timeFilter(created)\n  and\n  displayName in ('Fridge Temp','Freezer Temp')\nGROUP BY  1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "SELECT\nunix_timestamp(created) AS \"time\"\n,case when value='idle' then null \n      when value='heating' then 1 else null end as 'Heater'\n,case when value='idle' then null \n      when value='cooling' then 1 else null end as 'AC'\n,case when value='idle' then null\n      when value in ('fan only','fan') then 1 else null end as 'Fan'\nFROM thermostat\nWHERE\n  $__timeFilter(created)\n\nGROUP BY \nunix_timestamp(created)\nORDER BY created"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\nunix_timestamp(DateDTS) AS \"time\"\n,case when ProgramNM = 'Home' then 1 else null end as 'Home'\n,case when ProgramNM = 'HomeFan' then 1 else null end as 'HomeFan'\n,case when ProgramNM = 'Away' then 1 else null end as 'Away'\n,case when ProgramNM = 'AwayFan' then 1 else null end as 'AwayFan'\n,case when ProgramNM  in ('Sleep','Night') then 1 else null end as 'Sleep'\n,case when ProgramNM in ('SleepFan','NightFan') then 1 else null end as 'SleepFan'\n,case when ProgramNM = 'Windows' then 1 else null end as 'Windows'\n,case when ProgramNM = 'WindowsFan' then 1 else null end as 'WindowsFan'\n,case when ProgramNM not in ('Home', 'HomeFan', 'Solar', 'SolarFan', 'SolarMid', 'SolarMidFan', 'Away', 'AwayFan', 'Sleep', 'SleepFan', 'Windows', 'WindowsFan','NightFan','Night') then 1 else null end as 'Other'\n\nFROM ThermostatProgram\nWHERE\n  $__timeFilter(DateDTS)\n\n\n"
    }
   ]
  },
  {
   "title": "Ecobee",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "SELECT\nunix_timestamp(dateDTS) AS \"time\"\n,setPoint\n,currentTemperature\nFROM EcobeeStatus\nWHERE\n  $__timeFilter(DateDTS)\n\n\n"
    }
   ]
  }
 ]
}