{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\",\n  avg(vavg) as Temp\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nWHERE\n  $__timeFilter(created)\n  and\n  name =\"tempf\"\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(vavg) as Humidity\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nWHERE\n  $__timeFilter(created)\n  and\n  name in (\"humidityout\",'humidity')\nGROUP BY 1\nOrder by 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(vavg) as Pressures\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nWHERE\n  $__timeFilter(created)\n  and\n  name in (\"baromrel\",'baromrelin')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n UNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(vavg) as WindSpeed\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nWHERE\n  $__timeFilter(created)\n  and\n  name in (\"windSpeed\",'windspeedmph')\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "spectraphilic-windrose-panel",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\r\n  ,max(case when name in ('windSpeed','windspeedmph') then vmax else null end ) as 'speed'\r\n  ,max(case when name in ( 'windDirection','winddir') then vmax else null end) as 'direction'\r\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\r\nwhere\r\nname in ('windSpeed', 'windDirection','winddir','windspeedmph')\r\nand\r\n$__timeFilter(created)\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Combination",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name in ('tempout','tempf') then vavg else null end) as 'Temperature'\n  ,avg(case when name in ('humidityout','humidity') then vavg else null end) as 'Humidity'\n  ,avg(case when name in ('baromrel','baromrelin') then vavg else null end) as 'Pressure'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('tempout','humidityout','baromrel','tempf','baromrelin','humidity')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name in('tempout','tempf') then vavg else null end) as 'Temperature'\n,avg(case when name in ('illuminance','solarradiation') then vavg else null end) as 'light'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('tempout','illuminance','tempf','solarradiation')\n\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg( vavg ) as 'Humidity'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('humidityout','humidity')\nand\n$__timeFilter(created)\nGroup by  1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Rain (cumulative by event)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(created) AS \"time\"\n  ,avg(vavg ) as 'Rain'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('eventrain','eventrainin')\nand\n$__timeFilter(created)\nGroup by   unix_timestamp(created) \nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='illuminance' then vavg else null end) as 'Light'\n  ,avg(case when name='solarradiation' then vavg else null end) as 'Solar Radiation'\n\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere \nname in ('illuminance','solarradiation')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name='baromrel' then vavg else null end) as 'Pressure'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('baromrel')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,avg(case when name in ('windSpeed','windspeedmph') then vavg else null end) 'Wind'\n  ,avg(case when name in ('windGust','windgustmph') then vavg else null end) 'Wind Gusts'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('windSpeed', 'WindGust','windspeedmph','windgustmph')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Wind Speed Average",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created,30m)\n  ,avg(case when name in ('windSpeed','windspeedmph') then vavg else null end) 'Wind'\n  ,max(case when name in ('windGust','windgustmph') then vmax else null end) 'Wind Gusts'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere\nname in ('windSpeed', 'WindGust','windspeedmph','windgustmph')\nand\n$__timeFilter(created)\nGroup by  1\nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Lightning History",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  unix_timestamp(Time) AS \"time\"\r\n  ,Distance\r\nFROM Lightning\r\nwhere\r\n$__timeFilter(Time)\r\n\r\n"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(created)*1000 DIV $__interval_ms * $__interval_ms  AS \"time\"\n  ,max(vmax ) 'Wind Direction'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere \nname in ('windDirection','winddir')\nand\n$__timeFilter(created)\nGroup by   1\nORDER BY 1\n"
    }
   ]
  }
 ]
}