{
 "title": "Weather Trends by City",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "SLC Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(created) AS \"time\",\r\n  avg(vavg) as Temp\r\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\r\nWHERE\r\n  $__timeFilter(created)\r\n  and\r\n  name =\"tempf\"\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Houston Temp",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\nUNIX_TIMESTAMP(DateDTS)AS \"time\",\r\n  avg(value) as Temp\r\nFROM weatherMatthew\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\n  and\r\n  name =\"tempf\"\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "SLC",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"Actual High\"\r\n,DailyLow as \"Actual Low\"\r\n,HighestHigh as \"Record High\"\r\n,LowestLow as \"Record Low\"\r\n,AverageHigh as \"Average High\"\r\n,AverageLow as \"Average Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "CDA",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"Actual High\"\r\n,DailyLow as \"Actual Low\"\r\n,HighestHigh as \"Record High\"\r\n,LowestLow as \"Record Low\"\r\n,AverageHigh as \"Average High\"\r\n,AverageLow as \"Average Low\"\r\nfrom WeatherwithRecordsDynamicCDA\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Boise",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"Actual High\"\r\n,DailyLow as \"Actual Low\"\r\n,HighestHigh as \"Record High\"\r\n,LowestLow as \"Record Low\"\r\n,AverageHigh as \"Average High\"\r\n,AverageLow as \"Average Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Houston",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"Actual High\"\r\n,DailyLow as \"Actual Low\"\r\n,HighestHigh as \"Record High\"\r\n,LowestLow as \"Record Low\"\r\n,AverageHigh as \"Average High\"\r\n,AverageLow as \"Average Low\"\r\nfrom WeatherwithRecordsDynamicMatthew\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Average High and Low",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,AverageHigh as \"Boise High\"\r\n,AverageLow as \"Boise Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    },
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,AverageHigh as \"SLC High\"\r\n,AverageLow as \"SLC Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    },
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,AverageHigh as \"HOU High\"\r\n,AverageLow as \"HOU Low\"\r\nfrom WeatherwithRecordsDynamicMatthew\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Combined",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"SLC High\"\r\n,DailyLow as \"SLC Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    },
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"Boise High\"\r\n,DailyLow as \"Boise Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    },
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"HOU High\"\r\n,DailyLow as \"HOU Low\"\r\nfrom WeatherwithRecordsDynamicMatthew\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  }
 ]
}