{
 "title": "Trends Weather",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(created)) AS \"time\"\n  ,max(case when name='tempout' then vmax else null end) as 'Daily High'\n  ,min(case when name='tempout' then vmin else null end) as 'Daily Low'\n\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere name='tempout'\nand\n  $__timeFilter(created)\nGroup by   unix_timestamp(date(created)) \nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(created)) AS \"time\"\n  ,max(case when name='pressure' then vmax else null end) as 'Daily High'\n  ,min(case when name='pressure' then vmin else null end) as 'Daily Low'\n\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nwhere name='pressure'\nand\n  $__timeFilter(created)\nGroup by   unix_timestamp(date(created)) \nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Weather",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  unix_timestamp(date(created)) AS \"time\"\n  ,max(case when name='dailyRain' then vmax else null end) as 'Rain'\n  ,max(case when name='windGust' then vmax else null end) as 'Wind'\n  ,avg(case when name='humidityout' then vavg else null end) as 'Humidity'\nFROM (\n  SELECT name, created, value AS vmin, value AS vmax, value AS vavg\n    FROM weather WHERE $__timeFilter(created)\n  UNION ALL\n  SELECT name, bucket_start AS created, min_value AS vmin, max_value AS vmax, avg_value AS vavg\n    FROM weather_hourly WHERE $__timeFilter(bucket_start)\n) weather\nWHERE\n  $__timeFilter(created)\nGroup by   unix_timestamp(date(created)) \nORDER BY created\n"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT\n Unix_Timestamp(date(created)) AS \"time\"\n,avg(case when displayName in ('Master bed motion sensor') then value else null end) as 'Upstairs'\n\n,avg(case when displayName in ('Basement family motion','EcobeeSensor: Basement ecobee sensor (YBD6)') then value else null end) as 'Basement'\n,avg(case when displayName in ('Garage Motion on Home 3') then value else null end) as 'Garage'\n,avg(case when displayName in ('Cold storage water sensor') then value else null end) as 'Cold Storage'\nFROM temperatures\nWHERE\n  $__timeFilter(created)\nGROUP BY  Unix_Timestamp(date(created))\nORDER BY created"
    }
   ]
  },
  {
   "title": "Days High Above Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " Select unix_timestamp(DateDTS) as \"time\"\r\n,sum(case when DailyHigh>AverageHigh then 1 else 0 end) as \"Days Above Average High\"\r\n\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Days High Below Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " Select unix_timestamp(DateDTS) as \"time\"\r\n\r\n\r\n,sum(case when DailyHigh<AverageHigh then 1 else 0 end) as \"Days Below Average High\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Days Low Above Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " Select unix_timestamp(DateDTS) as \"time\"\r\n,sum(case when DailyLow>AverageLow then 1 else 0 end) as \"Days Above Average Low\"\r\n\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Days Low Below Average",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": " Select unix_timestamp(DateDTS) as \"time\"\r\n\r\n,sum(case when DailyLow<AverageLow then 1 else 0 end) as \"Days Below Average Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Weather with Records",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh as \"Actual High\"\r\n,DailyLow as \"Actual Low\"\r\n,HighestHigh as \"Record High\"\r\n,LowestLow as \"Record Low\"\r\n,AverageHigh as \"Average High\"\r\n,AverageLow as \"Average Low\"\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "High Difference from Average",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": " Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyHigh-AverageHigh\r\n\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\nGROUP BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Low Difference from Average",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": " Select unix_timestamp(DateDTS) as \"time\"\r\n,DailyLow-AverageLow\r\n\r\nfrom WeatherwithRecordsDynamic\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\nGROUP BY unix_timestamp(DateDTS)"
    }
   ]
  },
  {
   "title": "Yearly Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "rawSql": "Select unix_timestamp(DateDTS) as \"time\"\r\n,RainCumAMT as \"Current Year\"\r\n,AvgCumAMT as \"Historical Average\"\r\nfrom AnnualRain\r\nWHERE\r\n  $__timeFilter(DateDTS)"
    }
   ]
  },
  {
   "title": "Yearly Precipitation by Month",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    {
     "rawSql": "Select   unix_timestamp(MonthBeginDTS)  as \"time\"\r\n,sum(RainActualAMT)  as \"Current Year\"\r\n,sum(RainAverageAMT) as \"Historical Average\" \r\nfrom RainbyDay\r\nWHERE\r\n  $__timeFilter(DateDTS)\r\nGROUP BY 1\r\nOrder by 1"
    }
   ]
  }
 ]
}